### PR TITLE
RFC 0007 Add low profile memory scaling

### LINKED ISSUE #17: Memory-calculator blocks the application to run in container with memory limited to 512Mi
## What happened?
If I run a CNI image build by the java-azure buildpacks for a Spring Boot application in a container with only 512Mi memory, it will fail in the memory-calculator step and panic.

Repro steps:
1. build a CNI image from a Java application with the java-azure buildpacks
2. run the CNI image in a container with 512Mi memory limit (e.g., Kubernetes pod)
3. check the container status and logs

* What were you attempting to do?

    Run CNI image build by java-azure buildpacks in small-sized container.

* What did you expect to happen?

    The CNI image should be able to start with default configuration.

    In our case, we host the user application so we are not able to guess the configurations such as `BPL_JVM_HEAD_ROOM`, `BPL_JVM_LOADED_CLASS_COUNT` and `BPL_JVM_THREAD_COUNT`. If user do have requirement to customize the JVM configurations, they can specify through the `JAVA_OPTS` environment variable.

    Currently this memory-calculator step is mandatory. It will be great if we can pass in a configuration to disable the memory-calculator step in such scenarios.

* What was the actual behavior? Please provide log output, if possible.

    The default configuration prevents the application from starting, even before Java process is started.

    ```
    Adding $JAVA_OPTS to $JAVA_TOOL_OPTIONS
    unable to calculate memory configuration
    fixed memory regions require 631278K which is greater than 512M available for allocation: -XX:MaxDirectMemorySize=10M, -XX:MaxMetaspaceSize=119278K, -XX:ReservedCodeCacheSize=240M, -Xss1M * 250 threads
    ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/paketo-buildpacks_azul-zulu/helper/exec.d/memory-calculator': exit status 1
    ```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you using? Please include a version.

    kpack 0.3.1

* What buildpacks are you using? Please include versions.

    java-azure 5.8.1

* What builder are you using? If custom, can you provide the output from `pack inspect-builder <builder>`?

    Customized builder from kpack

* Can you provide a sample app or relevant configuration (`buildpack.yml`, `nginx.conf`, etc.)?

    A Spring Boot starter web application will do.

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by burl21**
## Summary
Implement [RFC 0007](https://github.com/paketo-buildpacks/rfcs/blob/main/text/java/0007-low-profile-memory-calc.md)  the memory calculator automatically scales stack size, reserved code cache, and thread count proportionally to the available memory. User configured values are always respected. A hard error is returned when the calculated heap would fall below the JVM minimum of ~~2M~~ 32M, with an actionable message guiding the user to reduce stack size, thread count, or code cache.

## Use Cases
Containers with less than 1G of memory (e.g. 256M, 512M) previously failed starts. This change makes the calculator usable in constrained environments without any user intervention.

Closes #17

## Checklist
* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

File: helper/memory_calculator.go [hunk 1]
```diff
@@ -167,31 +168,47 @@ func (m MemoryCalculator) Execute() (map[string]string, error) {
 		c.TotalMemory = calc.Size{Value: totalMemory}
 	}
 
-	r, err := c.Calculate(opts)
+	if c.TotalMemory.Value < calc.LowProfileThreshold {
+		c.LowProfile = true
```
Comment (dmikusa) [inline helper/memory_calculator.go]: This is how things were designed in the RFC, but I'm worried about the way we're triggering this behavior because someone will get opted into this automatically and may not notice. This will likely result in different JVM memory options, which might destabilize their app.

I think we should be a little more conservative here. Can you make the following changes?

1. When `c.TotalMemory.Value < calc.LowProfileThreshold` is true, let's log a `WARNING:` and say something like "The container memory is below the low memory profile threshold. In a future release, this will automatically activate the low memory profile, which may change the memory settings calculated for this application. Please check your application to see if this will have any impact or set BPL_LOW_MEMORY_PROFILE_DISABLED=true to disable the low memory profile.`

2. Check `BPL_LOW_MEMORY_PROFILE_DISABLED` to see if it's true. If it is then we opt-out of low profile calculations, which is a way for users to retain the existing behavior. For now, I think we should set this to `true` by default, so that we retain the existing behavior unless the user opts-in. We can then flip to false in a future release making it the default behavior.
How does that sound?

**Review by dmikusa — CHANGES_REQUESTED** [review]
This looks like an excellent start. Thanks for putting this together! I left you one note and I need to do some actual testing on this too. So far I have just reviewed the code.

File: helper/memory_calculator.go (hunk 1 above)
Comment (burl21) [reply helper/memory_calculator.go]: Thanks, sounds good. I would also recommend increasing the minimum allowed heap size from 2 MiB to either 32 MiB or 64 MiB. While the specification technically states a 2 MiB minimum, my tests show that, in practice, the JVM fails to start at that level.

Comment (dmikusa) [reply helper/memory_calculator.go]: Sounds reasonable to me. How about 32M.

**Comment by dmikusa** [comment]
One other thought, if you don't mind. We can safely add `-XX:+UseCompactObjectHeaders` when Java 25+ is used and it can reduce memory usage more.

**Comment by burl21** [comment]
Hi @dmikusa , I added the attribute but I’m not sure about the testing part. I tried to follow the existing ones and reused `testdata/3aa01010c0d3592ea248c8353d60b361231fa9bf9a7479b4f06451fef3e64524/stub-jre-11.tar.gz`
Let me know if new testdata needs to be created.
Thanks.

**Comment by burl21** [comment]
On second thought, I think I completely messed up the changes. Did you mean to add it only when low-profile is active? I think I need to do a rollback 😃

**Comment by anthonydahanne** [comment]
I did a review manually, and I had Claude also give me some feedback; here are "our" remarks:
* MinHeapSize : the PR and Java actual limit say 2M - but 32M is what is coded; I'm fine with 32M since I can't think people can start anything with under 32MB; sure, it changes the default behaviour so we'll have to be careful about user feedback
* The warning message says "A future release will automatically apply a low memory profile"  but the feature already exists in this release (just behind the flag). This is misleading. It should say something like  "To enable it now, set BPL_LOW_MEMORY_PROFILE_DISABLED=false." 
* one could argue the Java 25 changes could have been in another PR, but I won't ask you to rework it, that's fine - I'm still wondering if that should be the default for 25+, on one hand Java 25 is still "new" and it's time to make it default before everybody starts using it, OTOH I hope it won't break existing users...I'm an optimistic, let's try it out and monitor closely users feedback
* Claude said "Double-negation naming: BPL_LOW_MEMORY_PROFILE_DISABLED=false to enable the feature is counterintuitive and error-prone. Consider inverting to  BPL_LOW_MEMORY_PROFILE_ENABLED=true. This also makes the buildpack.toml default ("false") more natural. "  as you wish @burl21, I don't particularly care
* Claude said " Scaling floor for code cache: MinCodeCacheSize = 2496 * Kibi = ~2.4M (size.go:44). This floor is the JVM's initial tiered compilation threshold but is very small — at this  size JIT compilation essentially won't work. Consider whether this floor should also trigger a warning.  " - why not

Your work overall is a very good addition, thank you a lot, it's not everyday we have contributors putting their hands dirty in such a critical part of the buildpacks 🙇

**Comment by dmikusa** [comment]
> Claude said "Double-negation naming: BPL_LOW_MEMORY_PROFILE_DISABLED=false to enable the feature is counterintuitive and error-prone. Consider inverting to BPL_LOW_MEMORY_PROFILE_ENABLED=true. This also makes the buildpack.toml default ("false") more natural. " as you wish @burl21, I don't particularly care

I always have to look this up, but I believe the project has standardized around having the feature flag set to false by default and wording the property to fit that.

So if low memory profile is enabled by default and we want to disable it then I think `BPL_LOW_MEMORY_PROFILE_DISABLED=false` makes sense. It's not disabled by default.

I think we had discussions about what Claude is pointing out previously, and the consensus was that the project preferred to have things consistent with respect to having a feature flag false by default.

**Comment by dmikusa** [comment]
> On second thought, I think I completely messed up the changes. Did you mean to add it only when low-profile is active? I think I need to do a rollback 😃

Yes, I was thinking of adding that only when the low memory profile is used because setting `-XX:+UseCompactObjectHeaders` will reduce the memory overhead more.

It's not necessarily bad to add everywhere, but I'm not sure if buildpacks should be the one to make that choice. I think that's what @anthonydahanne was saying above too. Not sure it should be on for everyone. Can we add it just for low memory profile here, and if we want to add it for everyone, we add that in a separate PR?

File: helper/memory_calculator.go [hunk 2]
```diff
@@ -167,31 +168,58 @@ func (m MemoryCalculator) Execute() (map[string]string, error) {
 		c.TotalMemory = calc.Size{Value: totalMemory}
 	}
 
-	r, err := c.Calculate(opts)
+	if c.TotalMemory.Value < calc.LowProfileThreshold {
+		m.Logger.Bodyf("WARNING: Container memory is below %s. A future release will automatically "+
+			"apply a low memory profile, which adjusts JVM memory settings for small containers. "+
+			"To opt out, set BPL_LOW_MEMORY_PROFILE_DISABLED=true.",
```
Comment (dmikusa) [inline helper/memory_calculator.go]:
```suggestion
			"To opt out and retain the existing JVM memory settings, set BPL_LOW_MEMORY_PROFILE_DISABLED=true.",
```

Maybe to help clarify a little?

**Comment by burl21** [comment]
> * MinHeapSize : the PR and Java actual limit say 2M - but 32M is what is coded; I'm fine with 32M since I can't think people can start anything with under 32MB; sure, it changes the default behaviour so we'll have to be careful about user feedback

I updated the PR description. It was initially set to 2M, which is the value from the specification, but based on my tests that value is impractical. The JVM fails to start.

> * The warning message says "A future release will automatically apply a low memory profile"  but the feature already exists in this release (just behind the flag). This is misleading. It should say something like  "To enable it now, set BPL_LOW_MEMORY_PROFILE_DISABLED=false."

👍 

> * one could argue the Java 25 changes could have been in another PR, but I won't ask you to rework it, that's fine - I'm still wondering if that should be the default for 25+, on one hand Java 25 is still "new" and it's time to make it default before everybody starts using it, OTOH I hope it won't break existing users...I'm an optimistic, let's try it out and monitor closely users feedback

Yes, this was my mistake. I rolled it back and I’ll add the parameter only when the lower profile is active. There’s already a [JEP](https://openjdk.org/jeps/8361187) that should make it the default.


> * Claude said " Scaling floor for code cache: MinCodeCacheSize = 2496 * Kibi = ~2.4M (size.go:44). This floor is the JVM's initial tiered compilation threshold but is very small — at this  size JIT compilation essentially won't work. Consider whether this floor should also trigger a warning.  " - why not

From my research, the `MinCodeCacheSize` floor only kicks in when total memory is below ~11 MiB. At that point the calculator would already reject the configuration, the other fixed regions alone exceed that.

**Comment by burl21** [comment]
> Yes, I was thinking of adding that only when the low memory profile is used because setting `-XX:+UseCompactObjectHeaders` will reduce the memory overhead more.
> 
> It's not necessarily bad to add everywhere, but I'm not sure if buildpacks should be the one to make that choice. I think that's what @anthonydahanne was saying above too. Not sure it should be on for everyone. Can we add it just for low memory profile here, and if we want to add it for everyone, we add that in a separate PR?

The problem is that low profile is determined at runtime in the memory calculator, but the jvm version is only available at build time, it's never passed to the launch environment.
The simplest fix I see is adding a `BPI_JVM_VERSION` env var in `jre.go`/`jlink.go` (same pattern as `BPI_JVM_CLASS_COUNT`), then reading it in the memory calculator at runtime.

Does that make sense, or am I missing something?

**Comment by dmikusa** [comment]
@burl21 That sounds good to me. You're correct, that's the pattern we use to pass stuff from build to run time.

**Review by dmikusa — APPROVED** [review]

**Review by anthonydahanne — APPROVED** [review]
superb! thanks @burl21 !

**Comment by dmikusa** [comment]
Thanks @burl21 for this feature! This has been on the roadmap for a while. It's nice to see it included.

There is a little bit of work required to get this out in a usable state. @anthonydahanne and I are working on this and hope to have something out that you can use soon. I'll update this issue when we have something ready.

**Comment by burl21** [comment]
@dmikusa @anthonydahanne
Awesome, thanks for the guidance 😃
